config/routes.rb
Gochagames::Application.routes.draw do

  match '/login' => 'sessions#new', :as => :external_login, :via => :get
  match '/login' => 'sessions#create', :via => :post
  match '/logout' => 'sessions#destroy', :as => :logout, :via => [:delete, :post]
  match '/signup' => 'users#new', :as => :signup

  root :to => 'home#index'

  match '/trophies' => 'home#trophies', :as => :home_trophies

  resources :users, only: [:new, :create]
  resources :games, except: :destroy
  resources :players do
    member do
      get 'gamecard'
    end
    resources :trophies, only: [:new, :create, :destroy, :index]
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :genre, :title
  has_many :trophies

  validates_presence_of :title
end

app/models/player.rb
class Player < ActiveRecord::Base
  attr_accessible :birth_at, :email, :full_name, :username
  has_many :trophies

  validates_presence_of :username
  validates_uniqueness_of :username
  validates_uniqueness_of :email, allow_blank: :true
end

app/models/trophy.rb
class Trophy < ActiveRecord::Base
  belongs_to :game
  belongs_to :player
  attr_accessible :description, :points, :title, :game_id

  validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end


  before_filter :authenticate

  def authenticate
    #authenticate_or_request_with_http_basic do |username, pass|
      #username == "patito" && pass == "ivan"
    #end
    if session[:user_id].blank?
      redirect_to external_login_path
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.order("title DESC")

    if params[:q].present?
      @games = Game.where("title LIKE ?","%#{params[:q]}%")
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(params[:game])

    if @game.save
      redirect_to @game
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])

    if @game.update_attributes(params[:game])
      redirect_to @game
    else
      render :edit
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate

  def index
    @games = Game.all
  end

  def trophies
    @trophies = Trophy.order("points DESC")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @players = Player.order("players.username ASC").includes(:trophies)

    if params[:q].present?
      @players = @players.advanced_search(params[:q])
    end
  end

  def show
    @player = Player.find(params[:id])
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(params[:player])

    if @player.save
      redirect_to @player
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update_attributes(params[:player])
      redirect_to players_path
    else
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])

    if @player.destroy
      redirect_to players_path
    end
  end

  def gamecard
    @player = Player.find(params[:id])
    @trophies = @player.trophies.order("points DESC")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate

  def new
    if session[:user_id].present?
      redirect_to root_path
    end
  end

  def create
    @user = User.find_by_email(params[:email])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to external_login_path
  end
end

app/controllers/trophies_controller.rb
class TrophiesController < ApplicationController
  def index
    player = Player.find(params[:player_id])
    @trophies = player.trophies

    if params[:game_id].present?
      @trophies = @trophies.where("game_id = ?", params[:game_id])
    end

    render partial: "trophies_list", locals: { trophies: @trophies }, status: 200
  end

  def new
    @player = Player.find(params[:player_id])
    @trophy = @player.trophies.build
  end

  def create
    @player = Player.find(params[:player_id])
    @trophy = @player.trophies.build(params[:trophy])

    if @trophy.save
      redirect_to gamecard_player_path(@player)
    else
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trophies_helper.rb
module TrophiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<% if @game.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
    <ul>
    <% @game.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @game do |f| %>
  <p class="name">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p class="text">
    <%= f.label :genre %>
    <%= f.select :genre, Gochagames::Application.config.game_genres %>
  </p>
  <p class="submit">
    <%= f.submit %>
  </p>
<% end %>

app/views/games/edit.html.erb
<div id="content">
  <h1><%= "Editar #{@game.title}" %></h1>
  <%= render partial: "form" %>
</div>

app/views/games/index.html.erb
<div id="content">

  <%= form_tag  games_path, method: :get do %>
    <p class="submit">
      <%= text_field_tag :q, params[:q], autocomplete: 'off' %>
      <%= submit_tag "Buscar" %>
    </p>
  <% end %>
  <div class="boxed">
    <div class="content">
      <h1>Listado de Juegos</h1>
      <ul>
        <% @games.each do |game| %>
          <li>
            <table><tr><td><%= link_to game.title, game %></td><td><%= game.genre %></td></tr></table>
          </li>
        <% end %>
      </ul>
    </div>
    <p><%= link_to "Nuevo Juego", new_game_path %></p>
  </div>
</div>

app/views/games/new.html.erb
<div id="content">
  <h1>Crear un nuevo Juego</h1>
  <%= render partial: "form" %>
</div>

app/views/games/show.html.erb
<div class="post">
  <h2 class="title"><%= @game.title %></h2>
  <div class="meta">
    <p class="date"><%= @game.genre %></p>
  </div>
  <div class="story">
    <% if @game.trophies.any? %>
      <h2>Listado de Trofeos</h2>
      <ul>
        <% @game.trophies.each do |trophy| %>
          <li><%= trophy.title %></li>
        <% end %>
      </ul>
    <% else %>
      <em>No tiene ningun trofeo asociado</em>
    <% end %>
  </div>
  <p class="submit">
    <%= link_to "Editar", edit_game_path(@game) %>
  </p>
</div>

app/views/home/index.html.erb
<div id="gallery">
  <p><%= image_tag "img04.JPG", size: "700x299" %></p>
</div>
<div id="content">
  <div class="boxed">
    <div class="content">
      <h1>Listado de Juegos</h1>
      <ul>
        <% @games.each do |game| %>
          <li><%= game.title %></li>
        <% end %>
      </ul>
    </div>
  </div>
 </div>

app/views/home/trophies.html.erb
<div id="content">
  <div class="boxed js_trophies list">
    <%= render partial: "trophies/trophies_list", locals: {trophies: @trophies} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gocha Games</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <div id="logo">
      <h1><%= link_to "Gotcha Games", root_path %></h1>
      <%= image_tag "gameicon.png" %>
    </div>
    <div id="menu">
      <ul>
        <li class="active"><%= link_to "Games", games_path %></li>
        <li><%= link_to "Players", players_path %></li>
        <li><%= link_to "Trophies", home_trophies_path %></li>
        <li><a href="#" accesskey="3" title="">Ranking</a></li>
        <% if current_user %>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
      </ul>
    </div>
  </div>

<%= yield %>

  <div id="footer">
    <p id="copy">&copy;2007 Snow Flakes. Designed by <a href="#">Free CSS Templates</a></p>
  </div>
</body>
</html>

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <p class="name">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p class="name">
    <%= f.label :full_name, "Nombre Completo" %>
    <%= f.text_field :full_name %>
  </p>
  <p class="email">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p class="text">
    <%= f.label :birth_at, "Fecha de Nacimiento" %>
    <%= f.datetime_select :birth_at %>
  </p>
  <p class="submit">
    <%= f.submit %>
  </p>
<% end %>
<p>
  <%= link_to "Back", players_path %>
</p>

app/views/players/edit.html.erb
<div id="content">
  <h1>Editar Jugador</h1>
  <%= render partial: "form" %>
  <p><%= link_to "Borrar", @player, method: :delete, confirm: "Estas Seguro?" %>
</div>

app/views/players/gamecard.html.erb
<div class="content">
  <h2 class="title"><%= link_to @player.full_name, @player %></h2>
  <div class="meta">
    <p class="date">Puntos:<%= @player.trophies.sum("points") %></p>
  </div>
  <div class="boxed">
    <% if @player.trophies.any? %>

      <div class="boxed">
        <%= form_tag player_trophies_path(@player), id: "trophies_filter", method: :get, remote: true do %>
          <p class="submit">
            <%= select_tag :game_id, options_from_collection_for_select( Game.all, :id, :title), prompt: "All" %>
            <%= submit_tag "Filtrar" %>
          </p>
        <% end %>
      </div>

      <div class="boxed js_trophies_list">
        <%= render partial: "trophies/trophies_list", locals: {trophies: @trophies} %>
      </div>

    <% else %>
      <em> No Tiene Trofeos </em>
    <% end %>
  </div>
</div>

app/views/players/index.html.erb
<div id="content">

  <div class="boxed">
    <%= form_tag players_path, method: :get do %>
      <p class="submit">
        <%= text_field_tag :q, params[:q] %>
        <%= submit_tag "Buscar" %>
      </p>
    <% end %>
    <div class="content">
      <h1>Listado de Jugadores</h1>
      <ul>
        <% @players.each do |player| %>
          <li>
            <table>
              <tr>
                <td><%= link_to player.username, player %></td>
                <td><%= player.full_name %></td>
                <td><%= link_to "Editar", edit_player_path(player) %></td>
              </tr>
            </table>
          </li>
        <% end %>
      </ul>
    </div>
    <p><%= link_to "Nuevo Jugador", new_player_path %></p>
  </div>
</div>

app/views/players/new.html.erb
<div id="content">
  <h1>Crear un nuevo Jugador</h1>
  <%= render partial: "form" %>
</div>

app/views/players/show.html.erb
<div class="post">
  <h2 class="title"><%= @player.full_name %></h2>
  <div class="meta">
    <p class="date"><%= @player.username %></p>
  </div>
  <div class="story">
    <table>
      <tr>
        <th>Email</th><th>Nacido en:</th>
      </tr>
      <tr>
        <td><%= @player.email %></td><td><%= @player.birth_at %></td>
      </tr>
    </table>
    <p>
      <%= link_to "Game Card", gamecard_player_path(@player) %>
      <%= link_to "Nuevo Trofeo", new_player_trophy_path(@player) %>
    </p>
  </div>
  <p class="submit">
    <%= link_to "Editar", edit_player_path(@player) %>
  </p>
</div>

app/views/trophies/_trophies_list.html.erb
<h1>Listado de Juegos</h1>
<ul>
  <% trophies.each do |trophy| %>
    <li>
      <table>
        <tr>
            <td><%= trophy.title %></td>
            <td><%= trophy.description %></td>
            <td><%= "#{trophy.points} points" %></td>
          </tr>
          <tr>
            <td>by:<strong><%= trophy.game.title %></strong></td>
          </tr>
      </table>
    </li>
  <% end %>
</ul>

app/views/trophies/new.html.erb
<div id="content">
  <h1>Crear un nuevo Juego</h1>
  <%= form_for [@player, @trophy] do |f| %>
    <p class="name">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </p>
    <p class="text">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </p>
    <p class="text">
      <%= f.label :game_id %>
      <%= f.select :game_id, options_from_collection_for_select( Game.all, :id, :title) %>
    </p>
    <p class="text">
      <%= f.label :points %>
      <%= f.number_field :points %>
    </p>
    <p class="submit">
      <%= f.submit %>
    </p>
  <% end %>
<p>
  <%= link_to "Back", @player %>
</p>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div id="content">
  <h1>Crear un nuevo Usuario</h1>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this game from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <p class="name">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p class="password">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p class="password">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="submit">
    <%= f.submit %>
  </p>
<% end %>

</div>